# Generated by Django 3.0.7 on 2025-06-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTokendb',
            fields=[
                ('firstName', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('token', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer', models.IntegerField()),
            ],
        ),
    ]
